// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrayList: typeof import('./src/components/Fields/ArrayList.vue')['default']
    'ArrayList copy': typeof import('./src/components/Fields/ArrayList copy.vue')['default']
    ArrayTabs: typeof import('./src/components/Fields/ArrayTabs.vue')['default']
    CollapseButton: typeof import('./src/components/CollapseButton.vue')['default']
    DescriptionPopup: typeof import('./src/components/DescriptionPopup.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    FormInlineContainer: typeof import('./src/components/FormInlineContainer.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FormModal: typeof import('./src/components/FormModal.vue')['default']
    FormModalFullscreen: typeof import('./src/components/FormModalFullscreen.vue')['default']
    FormProvider: typeof import('./src/components/FormProvider.vue')['default']
    FormSteps: typeof import('./src/components/FormSteps.vue')['default']
    Test: typeof import('./src/components/Fields/Test.vue')['default']
  }
}

export { }
