// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrayFrom: typeof import('./src/components/Fields/ArrayFrom.vue')['default']
    CollapseButton: typeof import('./src/components/CollapseButton.vue')['default']
    DescriptionPopup: typeof import('./src/components/DescriptionPopup.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    FormInlineContainer: typeof import('./src/components/FormInlineContainer.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FormModal: typeof import('./src/components/FormModal.vue')['default']
    FormModalFullscreen: typeof import('./src/components/FormModalFullscreen.vue')['default']
    FormProvider: typeof import('./src/components/FormProvider.vue')['default']
    FormSteps: typeof import('./src/components/FormSteps.vue')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiInformation: typeof import('~icons/mdi/information')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    ObjectFrom: typeof import('./src/components/Fields/ObjectFrom.vue')['default']
  }
}

export { }
