// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrayField: typeof import('./src/components/Field/ArrayField.vue')['default']
    CheckboxField: typeof import('./src/components/Field/CheckboxField.vue')['default']
    CheckboxGroupField: typeof import('./src/components/Field/CheckboxGroupField.vue')['default']
    DateField: typeof import('./src/components/Field/DateField.vue')['default']
    FieldRenderer: typeof import('./src/components/Provider/FieldRenderer.vue')['default']
    FormInlineContainer: typeof import('./src/components/Layout/FormInlineContainer.vue')['default']
    FormModal: typeof import('./src/components/Layout/FormModal.vue')['default']
    FormModalFullscreen: typeof import('./src/components/Layout/FormModalFullscreen.vue')['default']
    FormProvider: typeof import('./src/components/Provider/FormProvider.vue')['default']
    FormRenderer: typeof import('./src/components/Provider/FormRenderer.vue')['default']
    NumberField: typeof import('./src/components/Field/NumberField.vue')['default']
    ObjectField: typeof import('./src/components/Field/ObjectField.vue')['default']
    PasswordField: typeof import('./src/components/Field/PasswordField.vue')['default']
    RadioField: typeof import('./src/components/Field/RadioField.vue')['default']
    SelectField: typeof import('./src/components/Field/SelectField.vue')['default']
    SliderField: typeof import('./src/components/Field/SliderField.vue')['default']
    SwitchField: typeof import('./src/components/Field/SwitchField.vue')['default']
    TextareaField: typeof import('./src/components/Field/TextareaField.vue')['default']
    TextField: typeof import('./src/components/Field/TextField.vue')['default']
    TimeField: typeof import('./src/components/Field/TimeField.vue')['default']
  }
}

export { }
