// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DemoRenderer: typeof import('./src/components/DemoRenderer.vue')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
  }
}

export { }
