<template>
  <div class="flex flex-col gap-4">
    <NCard :segmented="{content: true}" >
      <template #header>
        What is sweetforms ?
      </template>
      <div class="flex flex-col gap-2">
        <span>Sweetforms is an advance form generator based on <a href="" target="_blank">Naive UI</a> that offers high quality, highly customizable forms generated by defining an object structure. It has a lot of features including grid-based templating, responsiveness with a tailwindcss-like API, cross-field dependency, that can be used in async validation, field options (For select / radio / checkbox groups ...), a lot of field types, multi-steps forms, and many more features.
        It also supports complex field types like deeply nested array and objects. It benefits from Naive UI theming system, which means every style is overridable. It also supports dark / light mode</span>

        <span>This project is still in early development, and a lot of polishing will be achieved before releasing a version 1.0. A proper documentation and project roadmap will be delivered soon.</span>
        
        <NDivider />
        <h4>How to use ?</h4>

        <span>
          <h5>1. Install the package :</h5>
           <highlightjs language="js" :code="usageInstructions.one" class="overflow-x-auto rounded overflow-y-hidden" />
        </span>

        <span>
          <h5>2. Import the styles :</h5>
           <highlightjs language="js" :code="usageInstructions.two" class="overflow-x-auto rounded overflow-y-hidden" />
        </span>

        <span>
          <h5>3. Wrap your app with the FormProvider component :</h5>
           <highlightjs language="js" :code="usageInstructions.three" class="overflow-x-auto rounded overflow-y-hidden" />
        </span>

        <span>
          <h5>4. Use the form API anywhere in your app :</h5>
           <highlightjs language="js" :code="usageInstructions.four" class="overflow-x-auto rounded overflow-y-hidden" />
        </span>
      </div>
    </NCard>
    <div v-for="(DemoGroup, groupIndex) of demonstrations" :key="groupIndex" class="grid grid-cols-1 gap-4">
      <NCard :segmented="{content: true}" hoverable :title="label" v-for="({ label, value, expanded}, demoIndex) in DemoGroup" :key="demoIndex">
        <div class="flex flex-col gap-4" v-if="value">
          <div class="flex justify-center w-full items-center gap-8">
            <NButton @click="OpenForm(value)" type="primary">OPEN FORM</NButton>
            <n-switch v-model:value="demonstrations[groupIndex][demoIndex].expanded">
              <template #unchecked>SHOW FORM DEFINITION</template>
              <template #checked>HDE FORM DEFINITION</template>
            </n-switch>
          </div>         
          <NCollapseTransition :show="expanded">
            <highlightjs language="js" :code="'const form = ' + JSONstringifyWithFuncs(value)" class="overflow-x-auto rounded overflow-y-hidden" />
          </NCollapseTransition>
        </div>
        <div v-else class="w-full justify-center uppercase">EXAMPLES COMING SOON ...</div>
      </NCard>
    </div>
    
  </div>
</template>

<script setup lang="ts">
import { reactive } from "vue"
import { NCard, NButton, useThemeVars, NDivider, NCollapseTransition, NSwitch, useNotification } from "naive-ui"
import { FormProvider, useSweetform, SweetformTypes } from '@chronicstone/vue-sweetforms';
import * as AllDemos from "./demos/"
import { usageInstructions } from "./usageInstructions.js"
const demonstrations = reactive(Object.values(AllDemos).map((DemoGroup: any) => DemoGroup.map((demo: any) => ({ ...demo, expanded: false}))))


const { createForm, formInstances }: any = useSweetform()
const notif = useNotification()
const OpenForm = async (formContent: any) => {
  const { isCompleted, formData } = await createForm(formContent)
  notif[isCompleted ? 'success' : 'error']({
    title: isCompleted ? 'Form completed' : 'Form incomplete',
    content: JSON.stringify(formData, null, 4)
  })
}


function JSONstringifyWithFuncs(obj) {
  Object.prototype.toJSON = function() {
    var sobj = {}, i;
    for (i in this) 
      if (this.hasOwnProperty(i))
        sobj[i] = typeof this[i] == 'function' ?
          unescape(this[i].toString()) : this[i];

    return sobj;
  };
  Array.prototype.toJSON = function() {
      var sarr = [], i;
      for (i = 0 ; i < this.length; i++) 
          sarr.push(typeof this[i] == 'function' ? unescape(this[i].toString()) : this[i]);

      return sarr;
  };

  var str = JSON.stringify(obj, null, 4);

  delete Object.prototype.toJSON;
  delete Array.prototype.toJSON;

  return str;
}
const themeVars: any = useThemeVars()


</script>

<style>

</style>